# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FewBar.com - Make It Good
email: clint@fewbar.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website of Clint Byrum. Any words on here are
  expressly Clint's, and not those of whatever employer he has at
  the moment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spamaps.github.io" # the base hostname & protocol for your site
twitter_username: SpamapS
github_username:  SpamapS
permalink: "/:year/:month/:title/"

# Build settings
markdown: kramdown
